apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
      annotations:
        ad.datadoghq.com/mynginx.logs: '[{"source":"nginx"}]'
    spec:
      containers:
      - image: nginx
        name: mynginx
        ports:
        - containerPort: 80
